---
apiVersion: v1
kind: Service
metadata:
  name: shelly-plug
  labels:
    app.kubernetes.io/name: shelly-exporter-target
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: shelly-plug
subsets:
- addresses:
  - ip: 192.168.1.186
  - ip: 192.168.1.188
  ports:
  - name: http
    port: 80
