apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: shelly-exporter
resources:
- deployment.yaml
- service.yaml
- service-monitor-target.yaml
- service-monitor.yaml
