apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shelly-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: shelly-exporter
  endpoints:
  - interval: 10s
    port: metrics
